### ISSUE TITLE
Migration of content from earthsystemcog.org 

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/WGCM_Infrastructure_Panel#1]
[https://www.earthsystemcog.org/projects/wip/](https://www.earthsystemcog.org/projects/wip/ ) is retiring and pages need to migrated.

Open pages here, private pages to https://github.com/WCRP-CMIP/WGCM_Infrastructure_Panel_priv

Open pages are:

- Position papers -> CMIP6_Position_Papers.md
- Home : -> README.md
- About us -> README.md
- Resources : A collection of links to google docs --> Resources.md
- Contact : -> a line in README.md
- site media : -> collection of documents ... some listed on CMIP6_Position_Paper. Current plan is to puts those that are linked to in "Papers" and dump the rest into the private github repo.

1. The contact page has out of date contact info.
2. The About Us page has an outdated membership list.

**Comment by martinjuckes** [comment]
Resources page moved to [resources.md](resources.md)

**Comment by matthew-mizielinski** [comment]
I don't think there are any further actions here, closing
