### ISSUE TITLE
Add page with links to MIP tables from various projects

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/WGCM_Infrastructure_Panel#16]
In PCMDI/cmor#627 I've commented suggesting that the WIP pages could link to MIP table repositories for various projects

**Comment by durack1** [comment]
@wachsylon the way we have proceeded with non-CMIP6 variables, is to define these new - the [obs4mips-cmor-tables](https://github.com/PCMDI/obs4mips-cmor-tables/) repo is the best example.

The way these are defined, we pull all CMIP6 data request defined variables each time the tables are rewritten, and then add the obs4MIPs specific variables on top of the existing variables - this ensures consistency with the CMIP6 data, although I can't imagine we'll be seeing many more updates to the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/) or the data request now that 01.00.33 is finalized and released

**Comment by matthew-mizielinski** [comment]
Hi all, I've added [a page](https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel//cmor_and_mip_tables.html) to take CMOR links plus mip tables with all the information from the above.

@durack1 -- please have a quick look and shout if you have any suggestions, otherwise I'll close this down in a few days

@wachsylon -- please raise an issue here or let me know when you have a set of tables and any associated information  and I'll add links

**Comment by durack1** [comment]
@matthew-mizielinski this looks great to me, everything is there that I know about. @wachsylon we can add your PalMod2 tables to the bottom heading, if these don't currently exist (with public access), we can close this issue and another can be opened when these tables exist

**Comment by wachsylon** [comment]
@matthew-mizielinski @durack1 

Thank you for the efforts. I like the page with lists of tables. The question now is: where to put kind of "merge requests" for the list?

**Comment by matthew-mizielinski** [comment]
@wachsylon , if you can open a new issue and let me know the link I'll get it added next week
