### ISSUE TITLE
Add PMIP4 links

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/WGCM_Infrastructure_Panel#20]
The following was received by @taylor13 

From: <pmip-announce-request@lists.xx.fr>
Reply-To:  <c.brierley@xxx.ac.uk>
Date: Monday, September 13, 2021 at 8:31 AM
To: <pmip-announce@lists.xx.fr>
Subject: [PMIPn news] GitHub organisation and plotting repository

Dear All,

I just wanted to make you all aware of some things that we’ve been working on this summer to make access to PMIP data a little easier.

Firstly, I’ve set up an organisation on GitHub called “pmip4”. This will let us gather together pieces of code that are related to PMIP4 all in a single place. Anyone can join the organisation – just email me your github username and I’ll send along an invitation. Then you can create and upload your own repositories. The website for this organisation is https://pmip4.github.io/

Secondly, we have written up all the steps that that were taken to process the PMIP4 output for the midHolocene ensemble paper as a sort of user guide (we use the term “workflow”). There is a preprint of Zhao et al. at https://gmd.copernicus.org/preprints/gmd-2021-290/. As part of this effort, we also provide the code used and the interim data. This includes a single summary netcdf file for each PMIP4 simulation with some spatial patterns and timeseries and spreadsheets collating key metrics across the PMIP and DECK simulations (e.g. the summer rainfall in the North American Monsoon Domain). We have even created a Docker image, so you can get creating PMIP4 ensemble analyses from a single download. There is some initial documentation at https://pmip-p2fvar-analyzer.readthedocs.io/. Please check out and tell us when you (inevitably) come across an issue that we hadn’t thought of beforehand.

Cheers,
Chris

------------------------------------------------
Dr C. M. Brierley, 
Associate Professor in Climate Science,
UCL Dept. of Geography, University College London,
Rm 111, Northwest Wing,
Gower St, WC1E 6BT. 
W: +44 (0)20 7679 xxxx
-------

**Comment by matthew-mizielinski** [comment]
We could easily add a page on the MIPs with pointers such as this, but I wonder whether this should be linked from the  [WCRP CMIP6 MIP pages](https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/modelling-wgcm-cmip6-endorsed-mips) instead -- I'll ask Nico for some thoughts

**Comment by matthew-mizielinski** [comment]
@nico-caltabiano welcome!  Above is a communication from Chris Brierly, passed on by @taylor13, pointing out a github organisation (https://www.github.com/PMIP4) and an additional set of pages. 

We could add a table of MIPs with links to the WCRP pages and then add links such as these, or this information could be added to the WCRP page for PMIP4 -- any thoughts welcome.

**Comment by nico-caltabiano** [comment]
Thanks @matthew-mizielinski for the plug. I can certainly add this as a resource for PMIP4 directly on the page with the description of PMIP (https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/cmip6-endorsed-mips-article/1064-modelling-cmip6-pmip).

It just made me realise that all those endorsed MIPs pages may be out of date. As an example, on said PMIP page, the "Reference" is still "under review", with a date of 2016. It has now been fully published.

All that will eventually move to any website that is put together by the new IPO but I'll try to update before that.

**Comment by matthew-mizielinski** [comment]
Thanks @nico-caltabiano. I think adding links such as to the [PMIP github organization](https://github.com/PMIP4) and the [corresponding PMIP pages](https://pmip4.github.io/) to that page would be good. I'm pretty sure that there are a few more github organisations (e.g. CFMIP) that could be pointed to.

@durack1, I have not added a page for this in an attempt to avoid duplication across sites. We do have a direct link from the CMIP6 pages to the list of endorsed MIPs on the WCRP site, so I'm tempted to leave this alone for now.

**Comment by durack1** [comment]
@matthew-mizielinski agreed, I think many things are in a state of flux, but there is limited point in updating things until we have a clear path forward (likely owned by the IPO).
