### ISSUE TITLE
add info about CORDEX-CMIP6

### ISSUE THREAD

**Issue by gnikulin** [WCRP-CMIP/WGCM_Infrastructure_Panel#24]
here the first info about CORDEX-CMIP6 for the WIP webpage 

CORDEX-CMIP6 information 

CORDEX-CMIP6 Technical information
This page provides links to technical and scientific information about CORDEX-CMIP6

CORDEX-CMIP6 Science definition
Overview of CORDEX-CMIP6, Gutowski et al. (2016)
https://gmd.copernicus.org/articles/9/4087/2016/

CORDEX-CMIP6 Guidance
CORDEX experiment design for dynamical downscaling of CMIP6
https://cordex.org/experiment-guidelines/cordex-cmip6/experiment-protocol-rcms/

**Comment by matthew-mizielinski** [comment]
Hi @gnikulin,  I've added a cordex page (https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/cordex.html) with these links and a pointer at https://cordex.org at the top.

I'm happy to make any changes you can recommend here.
