### ISSUE TITLE
Data request: The link to the searchable list of variables does not work

### ISSUE THREAD

**Issue by IamJYC** [WCRP-CMIP/WGCM_Infrastructure_Panel#26]
The sites [Data Request web interface front page](http://clipc-services.ceda.ac.uk/dreq/index.html) and  [Search for variables](http://clipc-services.ceda.ac.uk/dreq/mipVars.html) are unavailable. If this is because the version which is linked is outdated, it would be great if you could update them.

**Comment by matthew-mizielinski** [comment]
Hi @IamJYC, looks like the whole webserver is down -- I've reported it to CEDA so hopefully it will be restarted in the next day or two.

**Comment by matthew-mizielinski** [comment]
The clipc-services.ceda.ac.uk web server hosting this has been rebooted and all appears to be working.

**Comment by IamJYC** [comment]
Hi @matthew-mizielinski, it seems that the server is down again. Could you please report it once more or I was wondering if there is a way I can report it directly to CEDA?

**Comment by matthew-mizielinski** [comment]
> Hi @matthew-mizielinski, it seems that the server is down again. Could you please report it once more or I was wondering if there is a way I can report it directly to CEDA?

Hi @IamJYC , I've poked CEDA support again and they'll reboot the web server later today (I've also asked about having this content moved). Should you want to contact CEDA directly then the address is `support __at__ ceda.ac.uk` (remove spaces and change `__at__` to `@`.

Should you wish to take a copy of the whole website I've previously used `wget --mirror --reject=xlsx <url>` to download everything other than the spreadsheets.
