### ISSUE TITLE
Updates to Lists of members

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/WGCM_Infrastructure_Panel#3]
WIP panel (as at October 2020)

Karl Taylor (Co-chair),  PCMDI/LLNL USA; 2014-
Matthew Mizielinski (Co-chair), Met Office, UK; 2018-
Ghaleb Abdulla,  LLNL, USA; 2019-
Sasha Ames, LLNL, USA; 2019-
Yuqi Bai, Tsinghua University, China; 2018-
Paul Durack, PCMDI/LLNL, USA; 2017-
David Hassell, NCAS, UK; 2019-
Martin Juckes, STFC, UK; 2014-
Slava Kharin, CCCma, Canada; 2014-
Michael Lautenschlager, DKRZ, Germany; 2014-
Ruth Petrie, NCAS, UK; 2019-; CDNOT Chair 2019-
Martina Stockhause, DKRZ, Germany; 2019-

Former Members

V. Balaji, Princeton/GFDL, USA; co-Chair 2014-2019
Luca Cinquini, NASA, USA; 2014-2019
Cecilia Deluca, NOAA, USA; 2014-2019
Sébastien Denvil, IPSL, France; 2014-2019; CDNOT Chair 2016-2019
Mark Elkington, Met Office, UK, 2014-2017
Eric Guilyardi, IPSL, France; 2014-2019
Bryan Lawrence, NCAS, UK; 2014-2019
Dean Williams, LLNL, USA; 2014-2019

Ex-officio:
Francesca Guglielmo, IPSL, France; 2014-

Note that a slightly out-of-date version of the above can be found at:   https://www.wcrp-climate.org/wgcm-cmip/wip

**Comment by martinjuckes** [comment]
@taylor13 : do you want me to transfer this to the README file, or should we simplify things by taking the list off our page and concentrating on getting WGCM to update their iist, so that there is only one list to worry about?

**Comment by matthew-mizielinski** [comment]
Given that we've put a bit of work into getting the wcrp pages up to date I've thrown in a pull request to strip this information from these pages.

**Comment by matthew-mizielinski** [comment]
Update made in #9 and typo fixed in #11. Change now live.

If no one shouts I'll close this in a few days

**Comment by durack1** [comment]
@matthew-mizielinski I think merge away, just close this out, as we have a streamlined WCRP page updating with Nico we can do these cleanups now
