### ISSUE TITLE
Add new project tables to CMOR MIP Tables overview page

### ISSUE THREAD

**Issue by wachsylon** [WCRP-CMIP/WGCM_Infrastructure_Panel#31]
@matthew-mizielinski 
Hi,
we finally can share the link to the repo including the tables:
https://gitlab.dkrz.de/dicad-pp/palmod2_dast

https://gitlab.dkrz.de/dicad-pp/palmod2_dast/-/tree/main/cmor_tables

Imo, the project has no strong focus on agreeing on common variable definitions which means that the tables will probably be updated from time to time.

Thank you for adding,
best,
Fabi

**Comment by matthew-mizielinski** [comment]
Hi @wachsylon , I've added this link in please have a quick look at https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel//cmor_and_mip_tables.html  and re-open this if I've missed anything.

**Comment by durack1** [comment]
@matthew-mizielinski thanks for catching this
